### ISSUE TITLE
bsp/board_api.h: No such file or directory

### ISSUE THREAD

**Issue by x893** [xrip/pico-xt#41]
Hello,
can you help me to fix below error ?
Thanks in advance

`
[ 17%] Building C object CMakeFiles/pico-xt.dir/drivers/usb/usb.c.obj
...\pico-xt\drivers\usb\usb.c:31:10: fatal error: bsp/board_api.h: No such file or directory
   31 | #include "bsp/board_api.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by xrip** [comment]
Hello,

You need latest TinyUSB lib version in `pico-sdk/lib/tinyusb `
`git pull` within that dir must be enought.

**Comment by x893** [comment]
Thanks, problem resolved
`
cd pico-sdk/lib/tinyusb
git pull
`
